services:
  db:
    image: postgres:15
    container_name: digit-db
    env_file:
      - ./.env
    volumes:
      - ./init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  account:
    build:
      context: ../../code/services/account
    container_name: digit-account
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  postgres_data: