openapi: 3.0.3
info:
  title: PGR (Public Grievance Redressal) Service API
  description: API for managing citizen service requests
  version: 1.0.0

servers:
  - url: http://localhost:8083
  - url: https://digit-lts.digit.org

security:
  - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    AuditDetails:
      type: object
      description: Embedded audit metadata
      properties:
        createdBy:
          type: string
        lastModifiedBy:
          type: string
        createdTime:
          type: integer
          format: int64
        lastModifiedTime:
          type: integer
          format: int64

    CitizenAddress:
      type: object
      description: Address linked to a citizen service
      properties:
        id:
          type: string
          format: uuid
        serviceRequestId:
          type: string
        address:
          type: string
        addressLine2:
          type: string
        city:
          type: string
        pincode:
          type: string
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
        auditDetails:
          $ref: '#/components/schemas/AuditDetails'

    CitizenService:
      type: object
      description: Citizen service request with workflow tracking
      properties:
        serviceRequestId:
          type: string
        tenantId:
          type: string
        serviceCode:
          type: string
        description:
          type: string
        accountId:
          type: string
        source:
          type: string
        applicationStatus:
          type: string
        action:
          type: string
        fileStoreId:
          type: string
        fileValid:
          type: boolean
        boundaryCode:
          type: string
        boundaryValid:
          type: boolean
        auditDetails:
          $ref: '#/components/schemas/AuditDetails'
        email:
          type: string
        mobile:
          type: string
        processId:
          type: string
        workflowInstanceId:
          type: string
        address:
          $ref: '#/components/schemas/CitizenAddress'

    ServiceWrapper:
      type: object
      properties:
        service:
          $ref: '#/components/schemas/CitizenService'
        workflow:
          type: object
          description: External workflow instance reference

    ServiceResponse:
      type: object
      properties:
        services:
          type: array
          items:
            $ref: '#/components/schemas/CitizenService'
        serviceWrappers:
          type: array
          items:
            $ref: '#/components/schemas/ServiceWrapper'

paths:

  /citizen-service/create:
    post:
      operationId: create
      tags: [Service]
      security:
        - bearerAuth: []
      x-pass-roles: true
      # x-pass-tenant: true   # add this later if create also needs tenantId in service call
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceWrapper'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'

  /citizen-service/update:
    post:
      operationId: update
      tags: [Service]
      security:
        - bearerAuth: []
      x-pass-roles: true
      # x-pass-tenant: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServiceWrapper'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'

  /citizen-service/search:
    get:
      operationId: search
      tags: [Service]
      security:
        - bearerAuth: []
      x-pass-tenant: true
      parameters:
        - in: query
          name: serviceRequestId
          schema:
            type: string
          required: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServiceResponse'
